# comment_macro
[package]
name = "comment_macro"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
mlua = {version = "0.11.2", features = ["luajit52", "vendored"]}
regex = "1.11.1"
