name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - name: Setup tools
        run: |
          nix profile install nixpkgs#xmake
          nix profile install nixpkgs#rustc
          nix profile install nixpkgs#cargo
      - uses: actions/checkout@v4
      - run: |
          xmake build
          xmake run test
